# Generated by Django 2.1.2 on 2018-11-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_friendly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=True, to='blogpost.Post', verbose_name='文章'),
        ),
    ]
