# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-31 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20181031_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='缩略图'),
        ),
    ]
