# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-01 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
