# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-01 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_dailysentence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailysentence',
            options={'ordering': ['-created_time'], 'verbose_name': '每日一句', 'verbose_name_plural': '每日一句'},
        ),
        migrations.AlterField(
            model_name='dailysentence',
            name='created_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
