# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-01 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0006_auto_20181101_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='图片')),
                ('content', models.TextField(verbose_name='内容')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.Post', verbose_name='文章详情')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.AlterModelOptions(
            name='dailysentence',
            options={'ordering': ['-pk'], 'verbose_name': '每日一句', 'verbose_name_plural': '每日一句'},
        ),
    ]
