# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-01 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0008_auto_20181101_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='is_activate',
            field=models.BooleanField(default=False, verbose_name='第一张'),
        ),
    ]
